[project]
name = "lesson77"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "t-taku-portfolio", email = "207686657+t-taku-portfolio@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
lesson77 = "lesson77:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
